-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 12:29:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smart_finance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart_finance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_finance` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `smart_finance` ;

-- -----------------------------------------------------
-- Table `smart_finance`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `agencia` INT(4) NULL,
  `conta` INT(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`subcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `subcategorias_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `smart_finance`.`categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`periodicidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`periodicidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`tipo_transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`tipo_transacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `subcategoria_id` INT NULL DEFAULT NULL,
  `periodicidade_id` INT NOT NULL,
  `tipo_transacao_id` INT NOT NULL,
  `banco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategoria_id` (`subcategoria_id` ASC) VISIBLE,
  INDEX `periodicidade_id` (`periodicidade_id` ASC) VISIBLE,
  INDEX `tipo_transacao_id` (`tipo_transacao_id` ASC) VISIBLE,
  INDEX `banco_id` (`banco_id` ASC) VISIBLE,
  CONSTRAINT `transacoes_ibfk_1`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `smart_finance`.`subcategorias` (`id`),
  CONSTRAINT `transacoes_ibfk_2`
    FOREIGN KEY (`periodicidade_id`)
    REFERENCES `smart_finance`.`periodicidade` (`id`),
  CONSTRAINT `transacoes_ibfk_3`
    FOREIGN KEY (`tipo_transacao_id`)
    REFERENCES `smart_finance`.`tipo_transacao` (`id`),
  CONSTRAINT `transacoes_ibfk_4`
    FOREIGN KEY (`banco_id`)
    REFERENCES `smart_finance`.`bancos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`historico_extratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`historico_extratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transacao_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `nome_arquivo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `transacao_id` (`transacao_id` ASC) VISIBLE,
  CONSTRAINT `historico_extratos_ibfk_1`
    FOREIGN KEY (`transacao_id`)
    REFERENCES `smart_finance`.`transacoes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`orcamento_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`orcamento_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `valor_orcado` DECIMAL(10,2) NOT NULL,
  `mes_referencia` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `orcamento_categorias_ibfk_1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `smart_finance`.`categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_finance`.`orcamento_subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_finance`.`orcamento_subcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subcategoria_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `valor_orcado` DECIMAL(10,2) NOT NULL,
  `mes_referencia` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategoria_id` (`subcategoria_id` ASC) VISIBLE,
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `orcamento_subcategorias_ibfk_1`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `smart_finance`.`subcategorias` (`id`),
  CONSTRAINT `orcamento_subcategorias_ibfk_2`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `smart_finance`.`categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
